# Ports collection makefile for:  pear-channel-twig
# Date created:			  23 april 2013
# Whom:				  Victor Pereira <v.pereira@packetwerk.de>
#

PORTNAME=	twig
PORTVERSION=	1.12.3
CATEGORIES=	devel www pear

MAINTAINER=	v.pereira@packetwerk.de
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.twig-project.org

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
